"""Controlled vocabulary of AI governance themes.

The mapping engine does not use an LLM. It resolves a free-text control
description to a small set of *themes* (this module), then to the framework
controls tagged with those themes (see the per-framework modules). Keeping the
theme layer separate means a new framework only has to tag its controls with
existing themes to become mappable, and it keeps the keyword lists in one
reviewable place.

Signal phrases are matched against normalised text (see ``mcp_ai_governance.text``).
Multi-word phrases score higher than single words because they are far less
ambiguous.
"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass, field
from typing import Final


@dataclass(frozen=True)
class Theme:
    """A governance theme and the surface forms that signal it in prose.

    Attributes:
        id: Stable machine identifier, referenced by framework control entries.
        label: Human-readable name used in rationales.
        signals: Lower-case phrases whose presence implies this theme.
    """

    id: str
    label: str
    signals: tuple[str, ...] = field(default=())


_THEME_LIST: Final[tuple[Theme, ...]] = (
    Theme(
        id="accountability",
        label="Accountability and roles",
        signals=(
            "accountability",
            "accountable",
            "roles and responsibilities",
            "responsibility",
            "raci",
            "ownership",
            "owner",
            "executive sponsor",
            "senior management",
            "senior leadership",
            "board oversight",
            "board of directors",
            "board",
            "ceo",
            "chief executive",
            "executive sign off",
            "decision rights",
            "sign off",
            "steering committee",
            "governance committee",
            "chain of command",
        ),
    ),
    Theme(
        id="policy",
        label="Policy and standards",
        signals=(
            "policy",
            "policies",
            "standard operating procedure",
            "procedure",
            "charter",
            "guideline",
            "code of conduct",
            "acceptable use",
            "prohibited use",
            "written policy",
            "approved policy",
            "written rules",
        ),
    ),
    Theme(
        id="inventory",
        label="AI system inventory",
        signals=(
            "inventory",
            "model registry",
            "system catalogue",
            "system catalog",
            "asset register",
            "register of systems",
            "discovery of ai",
            "shadow ai",
            "unapproved tools",
            "track which models",
        ),
    ),
    Theme(
        id="risk_assessment",
        label="Risk assessment and treatment",
        signals=(
            "risk assessment",
            "risk analysis",
            "risk register",
            "risk tolerance",
            "risk appetite",
            "risk treatment",
            "likelihood and impact",
            "threat modelling",
            "threat modeling",
            "residual risk",
            "risk tiering",
            "risk classification",
            "risk rating",
        ),
    ),
    Theme(
        id="impact_assessment",
        label="Impact assessment",
        signals=(
            "impact assessment",
            "fundamental rights",
            "human rights",
            "dpia",
            "fria",
            "affected individuals",
            "affected communities",
            "societal impact",
            "harm to individuals",
            "downstream harm",
            "environmental impact",
            "carbon footprint",
            "energy consumption",
            "sustainability",
        ),
    ),
    Theme(
        id="data_governance",
        label="Data governance and quality",
        signals=(
            "data governance",
            "data quality",
            "data lineage",
            "provenance",
            "training data",
            "dataset",
            "data set",
            "data preparation",
            "labelling",
            "labeling",
            "annotation",
            "representativeness",
            "data minimisation",
            "data minimization",
            "data acquisition",
            "data source",
            "corpus",
        ),
    ),
    Theme(
        id="privacy",
        label="Privacy and personal data",
        signals=(
            "privacy",
            "personal data",
            "personally identifiable",
            "pii",
            "gdpr",
            "anonymisation",
            "anonymization",
            "pseudonymisation",
            "pseudonymization",
            "consent",
            "data subject",
            "confidential data",
            "sensitive data",
        ),
    ),
    Theme(
        id="bias_fairness",
        label="Bias and fairness",
        signals=(
            "bias",
            "fairness",
            "discrimination",
            "discriminatory",
            "disparate impact",
            "protected class",
            "protected attribute",
            "demographic parity",
            "equitable",
            "equity",
            "subgroup performance",
        ),
    ),
    Theme(
        id="transparency",
        label="Transparency and explainability",
        signals=(
            "transparency",
            "disclosure",
            "disclose",
            "chatbot",
            "chat bot",
            "ai assistant",
            "virtual assistant",
            "conversational agent",
            "talking to an ai",
            "interacting with an ai",
            "machine generated",
            "explainability",
            "explainable",
            "interpretability",
            "model card",
            "system card",
            "notice to users",
            "inform users",
            "watermark",
            "content credentials",
            "label ai generated",
            "ai generated content",
            "synthetic content",
            "deepfake",
            "machine readable marking",
        ),
    ),
    Theme(
        id="documentation",
        label="Documentation and records",
        signals=(
            "documentation",
            "technical documentation",
            "design document",
            "specification",
            "documented",
            "written record",
            "artefact",
            "artifact",
            "datasheet",
        ),
    ),
    Theme(
        id="human_oversight",
        label="Human oversight",
        signals=(
            "human oversight",
            "human in the loop",
            "human on the loop",
            "human review",
            "human reviewer",
            "human approval",
            "manual review",
            # Bare "approve" and "approval" are deliberately absent: they fire
            # on "an approved policy", which is governance but not oversight.
            "must approve",
            "approve the output",
            "approve each",
            "requires approval",
            "approval required",
            "approval step",
            "reject",
            "veto",
            "sign off",
            "sign off before",
            "second pair of eyes",
            "four eyes",
            "maker checker",
            "override",
            "escalation path",
            "kill switch",
            "stop button",
            "approval gate",
            "approval workflow",
            "meaningful review",
            "human judgement",
            "human judgment",
        ),
    ),
    Theme(
        id="testing_evaluation",
        label="Testing and evaluation",
        signals=(
            "testing",
            "evaluation",
            "eval",
            "evals",
            "red team",
            "red teaming",
            "adversarial testing",
            "benchmark",
            "validation",
            "verification",
            "test set",
            "holdout",
            "tevv",
            "accuracy",
            "performance metric",
            "regression test",
            "acceptance criteria",
            "golden set",
            "measure quality",
        ),
    ),
    Theme(
        id="monitoring",
        label="Monitoring and drift",
        signals=(
            "monitoring",
            "monitor",
            "drift",
            "model decay",
            "post market",
            "postmarket",
            "telemetry",
            "observability",
            "continuous monitoring",
            "production monitoring",
            "alerting",
            "alert threshold",
            "dashboard",
            "in production",
        ),
    ),
    Theme(
        id="logging",
        label="Logging and traceability",
        signals=(
            "logging",
            "log",
            "logs",
            "audit log",
            "event log",
            "traceability",
            "record keeping",
            "recordkeeping",
            "immutable",
            "tamper evident",
            "retention period",
            "audit trail",
        ),
    ),
    Theme(
        id="security",
        label="Security",
        signals=(
            "security",
            "cybersecurity",
            "threat model",
            "adversarial attack",
            "prompt injection",
            "jailbreak",
            "access control",
            "authentication",
            "authorisation",
            "authorization",
            "least privilege",
            "encryption",
            "vulnerability",
            "penetration test",
            "model theft",
            "model extraction",
            "data poisoning",
            "supply chain attack",
            "secrets management",
        ),
    ),
    Theme(
        id="resilience",
        label="Robustness and resilience",
        signals=(
            "robustness",
            "robust",
            "resilience",
            "resilient",
            "failover",
            "availability",
            "backup",
            "disaster recovery",
            "redundancy",
            "graceful degradation",
            "degrade gracefully",
            "fail over",
            "degraded mode",
            "outage",
            "unavailable",
            "fallback",
            "rate limit",
        ),
    ),
    Theme(
        id="incident_response",
        label="Incident response",
        signals=(
            "incident",
            "incidents",
            "serious incident",
            "breach",
            "postmortem",
            "post mortem",
            "incident response",
            "remediation",
            "notification to authority",
            "report incidents",
            "malfunction",
            "root cause",
        ),
    ),
    Theme(
        id="third_party",
        label="Third-party and supply chain",
        signals=(
            "third party",
            "third parties",
            "vendor",
            "supplier",
            "procurement",
            "contract",
            "contractual",
            "service level agreement",
            "open source",
            "pre trained model",
            "pretrained model",
            "foundation model provider",
            "due diligence",
            "subprocessor",
            "outsourced",
            "api provider",
            "copyright",
            "intellectual property",
            "licensing",
        ),
    ),
    Theme(
        id="training_awareness",
        label="Training and AI literacy",
        signals=(
            "training programme",
            "training program",
            "awareness",
            "ai literacy",
            "literacy training",
            "upskilling",
            "competence",
            "competency",
            "onboarding curriculum",
            "certification of staff",
            "educate employees",
            "staff training",
            "employee training",
            "annual training",
            "mandatory training",
            "training curriculum",
            "training records",
            "role based training",
            "train employees",
            "train staff",
        ),
    ),
    Theme(
        id="lifecycle",
        label="Lifecycle and change management",
        signals=(
            "lifecycle",
            "life cycle",
            "development process",
            "deployment",
            "release process",
            "change management",
            "change control",
            "decommission",
            "retirement",
            "sunset",
            "versioning",
            "sdlc",
            "mlops",
            "ci cd",
            "promotion to production",
        ),
    ),
    Theme(
        id="feedback",
        label="Feedback, appeal and redress",
        signals=(
            "feedback",
            "complaint",
            "appeal",
            "redress",
            "grievance",
            "user report",
            "report a problem",
            "report an issue",
            "raise a concern",
            "stakeholder engagement",
            "consultation",
            "contest a decision",
            "right to explanation",
        ),
    ),
    Theme(
        id="conformity",
        label="Conformity assessment and certification",
        signals=(
            "conformity assessment",
            "ce marking",
            "declaration of conformity",
            "registration in the database",
            "notified body",
            "certification",
            "internal audit",
            "external audit",
            "management review",
            "nonconformity",
            "corrective action",
            "harmonised standard",
        ),
    ),
    Theme(
        id="purpose_scope",
        label="Intended purpose and scope",
        signals=(
            "intended purpose",
            "intended use",
            "use case",
            "scope of the system",
            "context of use",
            "business value",
            "requirements",
            "objectives",
            "foreseeable misuse",
            "out of scope",
            "out of scope use",
            "prohibited use",
            "deployment context",
            "known limitations",
        ),
    ),
)

THEMES: Final[Mapping[str, Theme]] = {theme.id: theme for theme in _THEME_LIST}

ALL_THEME_IDS: Final[frozenset[str]] = frozenset(THEMES)


def get_theme(theme_id: str) -> Theme:
    """Return the theme with ``theme_id``.

    Raises:
        KeyError: If the theme is not part of the controlled vocabulary.
    """
    return THEMES[theme_id]
